services:
  db:
    image: postgres:15
    container_name: orcamento_db
    restart: always
    environment:
      POSTGRES_DB: orcamento_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5434:5432" # Use a different host port to avoid conflicts
    volumes:
      - orcamento_postgres_data:/var/lib/postgresql/data
    networks:
      - orcamento_network

  orcamento_app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: orcamento_app
    restart: always
    ports:
      - "8082:8080" # Use a different host port
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/orcamento_db
      SPRING_DATASOURCE_USERNAME: user
      SPRING_DATASOURCE_PASSWORD: password
    depends_on:
      - db
    networks:
      - orcamento_network

volumes:
  orcamento_postgres_data:

networks:
  orcamento_network: