apiVersion: v1
kind: ConfigMap
metadata:
  name: orcamento-app-config
data:
  SPRING_DATASOURCE_URL: "jdbc:postgresql://postgres-svc.oficina-ns.svc.cluster.local:5432/orcamento_db"
  SPRING_DATASOURCE_USERNAME: "userOrcamentoDb"
