apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: oficina-ns

resources:
  - ../../base
  - namespace.yaml

commonLabels:
  tags.datadoghq.com/env: "prod"
  tags.datadoghq.com/version: "1.0.0"

patches:
  - path: configmap-patch.yaml
