apiVersion: v1
kind: Service
metadata:
  name: orcamento-orcamento-app-service
  namespace: oficina-ns
  labels:
    app: orcamento-app
spec:
  type: ClusterIP
  selector:
    app: orcamento-app
  ports:
  - protocol: TCP
    port: 80
    targetPort: 9091
