apiVersion: apps/v1
kind: Deployment
metadata:
  name: orcamento-app
  namespace: oficina-ns
  labels:
    app: orcamento-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: orcamento-app
  template:
    metadata:
      annotations:
        ad.datadoghq.com/orcamento-app.logs: '[{"source": "java", "service": "orcamento"}]'
      labels:
        app: orcamento-app
        admission.datadoghq.com/enabled: "true"
    spec:
      containers:
        - name: orcamento-app
          image: alexmarquesfa/orcamentooficina:latest
          imagePullPolicy: Always
          command: ["/bin/sh", "-c"]
          args:
            - |
              export OTEL_EXPORTER_OTLP_ENDPOINT="http://${DD_AGENT_HOST}:4318"
              exec java -jar app.jar
          ports:
            - containerPort: 9091
          env:
            - name: SPRING_DATASOURCE_URL
              valueFrom:
                secretKeyRef:
                  name: orcamento-secret
                  key: RDS_URL
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                configMapKeyRef:
                  name: orcamento-app-config
                  key: RDS_USERNAME
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: orcamento--secret
                  key: SPRING_DATASOURCE_PASSWORD
            - name: SERVER_PORT
              value: "9091"
            - name: ENV_NAME
              valueFrom:
                configMapKeyRef:
                  key: ENV_NAME
                  name: orcamento-app-config
            - name: ORDEM_SERVICO_WEBHOOK_URL 
              valueFrom:
                configMapKeyRef:
                  key: ORDEM_SERVICO_WEBHOOK_URL 
                  name: orcamento-app-config 
            - name: DD_AGENT_HOST
              valueFrom:
                fieldRef:
                  fieldPath: status.hostIP
          resources:
            requests:
              memory: "512Mi"
              cpu: "500m"
            limits:
              memory: "700Mi"
              cpu: "800m"

          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 9091
            initialDelaySeconds: 45
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3

          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 9091
            initialDelaySeconds: 45
            periodSeconds: 5
            timeoutSeconds: 3
            failureThreshold: 3
