apiVersion: v1
kind: ConfigMap
metadata:
  name: orcamento-app-config
data:
  ENV_NAME: "local"
  RDS_USERNAME: userOrcamentoDb
  ORDEM_SERVICO_WEBHOOK_URL: "http://ordem-servico-ordem-servico-app-service"
