apiVersion: v1
kind: Secret
metadata:
  name: orcamento-secret
  namespace: oficina-ns
type: Opaque
stringData:
  SPRING_DATASOURCE_PASSWORD: DB_PASSWORD_PLACEHOLDER
  RDS_URL: RDS_URL_PLACEHOLDER
  RDS_USERNAME: RDS_USERNAME_PLACEHOLDER
